name: free-programming-books-lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '6.x'
    - run: npm install -g free-programming-books-lint
    - run: fpb-lint .
